spring:
  application:
    name: database-poc
  profiles:
    active: localTest

server:
  port: 8080

---
spring:
  profiles: localTest
  jpa:
    database: postgresql
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

---
spring:
  profiles: cloudTest