spring:
  application:
    name: database-poc
  profiles:
    active: cloudTest

server:
  port: 8080

---
spring:
  profiles: localTest
  jpa:
    database: postgresql
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

---
spring:
  profiles: cloudTest
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  datasource:
    username: postgres
    password: "@Password123"
  cloud:
    gcp:
      sql:
        database-name: postgres
        instance-connection-name: client-intelligence-705116:europe-west2:poc-postgesql-01
        credentials.location: file:/C:/Users/thoma/Documents/csv_poc/gcp-cred.json
      project-id: Client Intelligence 705116