spring:
  application:
    name: database-poc
  profiles:
    active: cloudTest

server:
  port: 8080

---
spring:
  profiles: localTest
  jpa:
    database: postgresql
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

---
spring:
  profiles: cloudTest
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    username:
    password:
  cloud:
    gcp:
      sql:
        database-name:
        instance-connection-name:
        credentials.location:
      project-id:
  bigquery:
    credentialsLocation:
    credentialsName:
    projectId:
  elasticsearch:
    host:
    port: